name: Build and Run Frontend Container

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # Use Ubuntu GitHub runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t frontend-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 frontend-app

    - name: Wait for the application to start
      run: |
        sleep 5  # Ensure the app has started before testing

    - name: Test if frontend is running
      run: |
        curl --silent --fail http://localhost:8080 || exit 1

    - name: Stop Docker container
      run: |
        docker ps -q | xargs docker stop
