name: Build and Run Frontend Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t frontend-app -f ./FrontEnd/Dockerfile ./FrontEnd

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 frontend-app

    - name: Wait for the application to start
      run: |
        sleep 15  # Increased wait time to allow the container to fully start

    - name: Capture container ID
      id: capture_container_id
      run: |
        container_id=$(docker ps -q)
        echo "::set-output name=container_id::$container_id"  # Save the container_id as output

    - name: View Docker container logs
      run: |
        echo "Container ID: ${{ steps.capture_container_id.outputs.container_id }}"
        docker logs ${{ steps.capture_container_id.outputs.container_id }}  # Use the output from previous step

    - name: Test if frontend is running
      run: |
        docker exec ${{ steps.capture_container_id.outputs.container_id }} curl --silent --fail http://localhost:8080 || exit 1  # Access container directly with curl

    - name: Stop Docker container
      run: |
        docker stop ${{ steps.capture_container_id.outputs.container_id }}  # Stop the container after the tests
