name: Build and Run Frontend Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t frontend-app -f ./FrontEnd/Dockerfile ./FrontEnd

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 frontend-app

    - name: Wait for the application to start
      run: |
        sleep 30  # Increased wait time to allow the container to fully start

    - name: Capture container ID
      id: container_id
      run: |
        container_id=$(docker ps -q)
        echo "container_id=$container_id" >> $GITHUB_ENV

    - name: View Docker container logs
      run: |
        docker logs ${{ env.container_id }}  # Use the container ID from the previous step

    - name: Test if frontend is running
      run: |
        curl --silent --fail http://localhost:8080 || exit 1  # Check if app is accessible

    - name: Stop Docker container
      run: |
        docker stop ${{ env.container_id }}  # Stop the container after the tests
