name: Build and Run Frontend Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t frontend-app -f ./frontend/Dockerfile ./frontend

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 frontend-app

    - name: Wait for the application to start
      run: |
        # Increase the sleep time to give more time for the app to start
        sleep 10  # Wait 10 seconds for the container to fully start

    - name: Test if frontend is running
      run: |
        # Check if the frontend is accessible
        curl --silent --fail http://localhost:8080 || exit 1

    - name: Stop Docker container
      run: |
        docker ps -q | xargs docker stop
